### ISSUE TITLE
[New] Tính năng QR Code đăng nhập vào Hub

### ISSUE THREAD

**Issue by NgocDo1403** [huongvu0210/D-n-Similac#1]
**A.	Quy trình thực hiện**
Quà 1: Quà dành cho nữ hộ sinh tham gia sự kiện
Quà 2: Quà dành cho nữ hộ sinh không tham gia sự kiện

**Trường hợp 1: Không có QR Code**
1.	Abbott cung cấp danh sách:
a.	Bệnh viện
b.	Sale-rep
2.	Medihub sẽ cung cấp cho Abbott:
a.	Danh sách code: bệnh viện, tên sale-rep
3.	Tại sự kiện:
a.	Sale-rep cung cấp code cho nữ hộ sinh để đăng ký. Phase 1 không nhận điểm.
b.	Nữ hộ sinh sẽ nhận được phần quà 1.
4.	Sau sự kiện:
a.	Sale-rep cung cấp code cho nữ hộ sinh để đăng ký
b.	Nữ hộ sinh sẽ nhận được phần quà (khác với sự kiện)
5.	Medihub sẽ tracking được:
a.	Thông tin đăng ký của nữ hộ sinh:
(1)	Họ tên
(2)	Ngày tháng năm sinh
(3)	Cơ quan công tác
(4)	Chức danh
b.	Nữ hộ sinh đăng ký từ:
(1)	Sự kiện/ bệnh viện: hoạt động hội thảo offline diễn ra sau kick-off (khoảng 10 bệnh viện). 
(2)	Không từ sự kiện: Sale-rep mời nữ hộ sinh tham gia

**Trường hợp 2: Có QR Code**
1.	Abbott cung cấp danh sách:
a.	Bệnh viện
b.	Sale-rep
2.	Medihub sẽ cung cấp cho Abbott:
a.	Danh sách code: bệnh viện, tên sale-rep
b.	Các mã QR code theo danh sách trên
3.	Tại sự kiện:
a.	Sale-rep cung cấp code cho nữ hộ sinh để đăng ký.
b.	Hoặc nữ hộ sinh dùng MDCom quét mã QR code của sale-rep.
Quét QR code sẽ kích hoạt Hub. Phase 1 không nhận điểm.
c.	Nữ hộ sinh sẽ nhận được phần quà 1.
4.	Sau sự kiện:
a.	Sale-rep cung cấp code cho nữ hộ sinh để đăng ký
b.	Hoặc nữ hộ sinh dùng MDCom quét mã QR code của sale-rep
c.	Nữ hộ sinh sẽ nhận được phần quà (khác với sự kiện)
5.	Medihub sẽ tracking được:
a.	Thông tin đăng ký của nữ hộ sinh:
(1)	Họ tên
(2)	Ngày tháng năm sinh
(3)	Cơ quan công tác
(4)	Chức danh
b.	NHS đăng ký từ:
(1)	Sự kiện/ bệnh viện: hoạt động hội thảo offline diễn ra sau kick-off (khoảng 10 bệnh viện). 
(2)	Không từ sự kiện: Sale-rep mời nữ hộ sinh tham gia
(3)	Loại quà đã nhận: Chỉ cần tracking được Nữ hộ sinh đã nhận được quà 1 hay quà 2.
 
**B.	Tính năng trên mobile:**
1.	Nhập 2 code theo file proposal gửi khách hàng.
2.	Scan QR 1 lần.
3.	Màn hình home của hub Similac giống file XD đã gửi. Với các tính năng chưa có, tạm thời hiện thông báo “Tính năng này sẽ được mở vào ngày [Theo timeline]” hoặc thông báo tương tự.
4.	Không có icon chuông noti thông báo
5.	Không có tính năng lưu trữ tin tức
6.	Kích thước hình ảnh tin tức do mobile-dev quy định

**Comment by huongvu0210** [comment]
https://user-images.githubusercontent.com/78403286/106568697-34182800-6566-11eb-8019-8d43f7b88fa9.mp4
